### ISSUE TITLE
'NoneType' object has no attribute 'voice_state' when sharding

### ISSUE THREAD

**Issue by GamingGeek** [EvieePy/Wavelink#23]
Hey, I started sharding my bot (not necessarily needed right now, just testing things) and I came across this issue whenever someone tries to play a song.
```py
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Administrator\Documents\Geek\Fire\cogs\music.py", line 460, in play_
    await ctx.invoke(self.connect_)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\context.py", line 132, in invoke
    ret = await command.callback(*arguments, **kwargs)
  File "C:\Users\Administrator\Documents\Geek\Fire\cogs\music.py", line 450, in connect_
    await player.connect(channel.id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wavelink\player.py", line 189, in connect
    await self._get_shard_socket(guild.shard_id).voice_state(self.guild_id, str(channel_id))
AttributeError: 'NoneType' object has no attribute 'voice_state'
```

The code I'm using is a slightly modified version of the [advanced example](https://github.com/EvieePy/Wavelink/blob/master/examples/advanced/advanced.py)

**Comment by GamingGeek** [comment]
Ah, just realized I was running an older version of wavelink. I updated and it's been fixed.
